export const portfolioData = {
  name: 'Yan Firdaus, S.H., CHRM., CPDA',
  title: 'HR Strategy & Organizational | Performance | Leadership Development & Empowering Leaders | Building HR Systems & Analytics',
  subtitle: '',
  intro: 'Human Capital professional with 15+ years Experience and 10 Years of specialized experience in Human Capital Development, HCGA, and Organizational Development. Expert in HR digitalization, leadership development, and aligning HR strategies with business objectives to drive organizational effectiveness.',
  image: '/gallery/pp.png',

  about: {
    description: 'Human Capital professional with more than 8 years of specialized experience in Human Capital, HCGA, and Organizational Development, supported by a total of 15 years of professional experience across mining, operational, and corporate environments. Experienced in Human Capital Development, Organizational Development, Industrial Relations, Recruitment & Talent Management, Leadership Development, HR Operations, workforce planning, HR system development, and General Affairs management.\n\nProven capability in developing HR systems, building web-based HR applications, handling industrial relations matters, and aligning HR strategies with business objectives to support organizational effectiveness and sustainable business growth. Successfully delivered leadership development programs for more than 250+ employees across multiple operational locations and organizational levels.',
    expertise: [
      {
        title: 'Human Capital Strategy',
        description: 'Strategic HR planning aligned with business objectives for organizational growth',
        icon: '🎯',
      },
      {
        title: 'Organizational Development',
        description: 'Building high-performance teams through culture transformation and capability development',
        icon: '📊',
      },
      {
        title: 'Leadership Development',
        description: 'Coaching and mentoring for emerging and executive leaders across 250+ professionals',
        icon: '👔',
      },
      {
        title: 'HR Digitalization',
        description: 'Building web-based HR applications and HRIS systems for operational excellence',
        icon: '💻',
      },
      {
        title: 'Mining & Operational',
        description: 'Deep expertise in mining operations and dynamic site-based environments',
        icon: '⛏️',
      },
    ],
  },

  experience: [
    {
      company: 'PT Sarana Sukses Sejahtera & PT Gunungmas Sukses Makmur',
      position: 'Head of Human Capital Development',
      period: 'May 2025 – Present',
      location: 'North Jakarta, Indonesia',
      description: 'Lead Human Capital Development strategy and organizational development initiatives. Manage recruitment, talent management, leadership development, and performance management programs. Develop HR systems, SOPs, and people development strategies aligned with business objectives.',
      keyContributions: [
        'Built and implemented Integrated HR Management System',
        'Designed Leadership Activity Application and Employee Leave Request Application',
        'Delivered leadership development programs across multiple operational locations',
      ],
    },
    {
      company: 'PT Fajar Anugerah Dinamika (Hasnur Group) – Site PT Berau Coal',
      position: 'HCGA Department Head',
      period: 'March 2023 – May 2025',
      location: 'East Kalimantan, Indonesia',
      description: 'Managed end-to-end HCGA operations within mining operational environment. Led manpower planning, recruitment, industrial relations, compensation & benefits, and workforce management. Oversaw General Affairs operations and managed budgeting and forecasting.',
      keyContributions: [
        'Managed 250+ trained leaders across 8 operational locations',
        'Supported organizational development and people management initiatives',
        'Improved HR operational coordination and workforce support processes',
      ],
    },
    {
      company: 'PT Bahtera Putera Nusantara – Site Wahana Agung Sejahtera (WAS)',
      position: 'HCGA Section Head',
      period: 'August 2022 – December 2022',
      location: 'Indonesia',
      description: 'Managed HCGA operational activities within site operational environment. Handled manpower management, recruitment, industrial relations, General Affairs operations, transportation coordination, accommodation management, and operational workforce support.',
      keyContributions: [
        'Supported operational workforce management and manpower coordination',
        'Improved coordination of operational support services',
        'Enhanced HR operational effectiveness and employee support processes',
      ],
    },
    {
      company: 'PT Electra Global – Coal Mining Operation',
      position: 'HR Manager',
      period: 'August 2019 – May 2022',
      location: 'Central Kalimantan, Indonesia',
      description: 'HR operational activities within operational and mining environments. Handled Industrial Relations matters, employee performance management processes, manpower forecasting, and workforce administration aligned with operational and business needs.',
      keyContributions: [
        'Improved HR administrative coordination and workforce management processes',
        'Supported recruitment, manpower planning, and employee relations activities',
        'Assisted Industrial Relations handling and employee performance management',
        'Supported organizational effectiveness within mining operational environments',
        'Supported manpower forecasting aligned with operational business requirements',
      ],
    },
    {
      company: 'PT Limoff Internasional Indonesia',
      position: 'Acquisition Manager',
      period: 'February 2016 – September 2018',
      location: 'Bali, Indonesia',
      description: 'Managed merchant acquisition, business partnership development, and operational coordination. Conducted market research, business development initiatives, and customer relationship management to support business growth and operational effectiveness, In addition, supported recruitment activities, workforce planning, employee relations, and HR operational administration. Assisted in handling Industrial Relations matters, employee performance monitoring, and manpower forecasting aligned with operational and business needs.',
      keyContributions: [
        'Drove merchant acquisition and business development initiatives',
        'Supported recruitment and workforce planning activities',
        'Assisted employee relations and HR operational processes',
        'Supported manpower forecasting and operational coordination',
        'Enhanced customer relationship management and service effectiveness',
        'Enhanced customer relationship management and service effectiveness',
      ],
    },
    {
      company: 'Ramita Realty Group (Ramita Villa Legian & Ubud Bali)',
      position: 'Assistant Manager',
      period: 'March 2014 – June 2017',
      location: 'Bali, Indonesia',
      description: 'Supported operational management, business coordination, and Human Resources administration within dynamic operational environments. Managed operational reporting, workforce monitoring, employee administration, and coordination activities to support operational effectiveness and organizational performance.',
      keyContributions: [
        'Supported operational management and business coordination',
        'Managed reporting and operational monitoring',
        'Supported HR administration and employee coordination',
        'Assisted manpower administration and operational activities',
        'Enhanced customer relations and operational effectiveness',
      ],
    },
    {
      company: 'iFive Store, Ambarukmo Plaza Yogyakarta',
      position: 'Technical Support Specialist',
      period: 'March 2014 – June 2017',
      location: 'Bali, Indonesia',
      description: 'Supported operational management, business coordination, and Human Resources administration within dynamic operational environments. Managed operational reporting, workforce monitoring, employee administration, and coordination activities to support operational effectiveness and organizational performance.',
      keyContributions: [
        'Supported operational management and business coordination',
        'Managed reporting and operational monitoring',
        'Supported HR administration and employee coordination',
        'Assisted manpower administration and operational activities',
        'Enhanced customer relations and operational effectiveness',
      ],
    },
  ],

  projects: [
    {
      title: 'Talent Management & Succession Planning Framework',
      category: 'Human Capital Strategy',
      description: 'Designed and implemented a talent management and succession planning framework to identify high-potential employees, develop leadership pipelines, and ensure business continuity for critical positions.',
      achievements: [
        'Mapped critical positions and leadership continuity risks',
        'Built a structured high-potential employee identification framework',
        'Created succession pipelines for future leadership readiness',
      ],
      tags: ['Talent Management', 'Succession Planning', 'Leadership Pipeline'],
      image: '/projects/talent-management.png',
    },
    {
      title: 'Human Capital Analytics Dashboard',
      category: 'HR Analytics & Digitalization',
      description: 'Developed a Human Capital Analytics Dashboard integrating workforce, turnover, training, and performance metrics to support data-driven decision making.',
      achievements: [
        'Integrated workforce, turnover, training, and performance indicators',
        'Enabled management visibility into key human capital trends',
        'Improved evidence-based HR planning and decision support',
      ],
      tags: ['HR Analytics', 'Dashboard', 'Data-Driven HR'],
      image: '/projects/hc-dashboard.png',
    },
    {
      title: 'NOVI AI Human Capital Assistant',
      category: 'AI & HR Innovation',
      description: 'Developed NOVI, an AI-powered Human Capital Assistant for HR knowledge management, employee support, policy guidance, and organizational learning.',
      achievements: [
        'Built an AI assistant concept for HR knowledge management',
        'Supported employee guidance on policies, processes, and learning topics',
        'Introduced AI-enabled HR service support and organizational learning',
      ],
      tags: ['AI Assistant', 'HR Innovation', 'Knowledge Management'],
      image: '/projects/novi.png',
    },
    {
      title: 'Empowering Leaders Development Program',
      category: 'Leadership Development',
      description: 'Comprehensive leadership development program with coaching and mentoring excellence',
      achievements: [
        'Trained 250+ emerging leaders across organization',
        'Created structured career pathway for high-potential employees',
        'Developed leaders across all departments and operational locations',
      ],
      tags: ['Leadership Development', 'Coaching', 'Talent Pipeline'],
      image: '/gallery/project-leadership.png',
    },
    {
      title: 'Psikotest Assessment System - Web-Based',
      category: 'HR Digitalization',
      description: 'Web-based psychological testing and employee assessment platform designed to digitalize recruitment, evaluation, and competency measurement processes.',
      achievements: [
        'Developed end-to-end online psychological assessment platform',
        'Digitalized recruitment and employee evaluation processes',
        'Improved assessment efficiency, reporting, and data management',
      ],
      tags: ['HR Digitalization', 'Assessment', 'Web Applications'],
      image: '/gallery/test.png',
    },
    {
      title: 'HR Integrated Management System (HR IMS)',
      category: 'HR Systems',
      description: 'Custom web-based HRIS platform for centralized HR operations and data management',
      achievements: [
        'Automated HR workflows and processes',
        'Enabled data-driven organizational decision-making',
        'Integrated across all operational locations',
      ],
      tags: ['HRIS', 'Digital Transformation', 'HR Systems'],
      image: '/gallery/ims.png',
    },
    {
      title: 'Employee Leave Request Application',
      category: 'HR Operations Automation',
      description: 'Automated leave management system for streamlined approval workflows',
      achievements: [
        'Reduced leave administration time by 70%',
        'Improved leave tracking accuracy',
        'Enabled self-service employee management',
      ],
      tags: ['HR Systems', 'Automation', 'Employee Portal'],
      image: '/gallery/hcapp.png',
    },
    {
      title: 'Fresh Mechanic Development Program (FMDP)',
      category: 'Technical Development',
      description: 'Comprehensive mechanical and technical competency development for high school graduates',
      achievements: [
        'Trained 50+ mechanics with technical expertise',
        'Developed maintenance capability across organization',
        'Created standardized technical training curriculum',
      ],
      tags: ['Technical Development', 'Mechanical Training', 'Skills Building'],
      image: '/gallery/fmdp2.jpg',
    },
    {
      title: 'Operator Development Program (ODP)',
      category: 'Operational Excellence',
      description: 'Specialized training program transforming high school graduates into skilled heavy equipment operators',
      achievements: [
        'Trained 50+ operators for mining operations',
        'Created structured technical competency framework',
        'Ensured operational readiness across all sites',
      ],
      tags: ['Technical Training', 'Skills Development', 'Operational Excellence'],
      image: '/gallery/odp1.png',
    },
  ],

  certifications: [
    {
      id: 'ef-set-c1-2026',
      title: 'EF SET Certified (C1 Advanced)',
      issuer: 'EF SET',
      year: 2026,
      category: 'Language Certification',
      preview: '/credentials/previews/ef-set-c1-2026.webp',
      pdf: '/credentials/ef-set-c1-2026.pdf',
      featured: true,
    },
    {
      id: 'professional-life-coach-2025',
      title: 'Certified Professional Life Coach',
      issuer: 'ALISON',
      year: 2025,
      category: 'Professional Certification',
      preview: '/credentials/previews/professional-life-coach-2025.webp',
      pdf: '/credentials/professional-life-coach-2025.pdf',
      credentialId: '4416-50727258',
      verificationUrl: 'https://alison.com/verify/daefe07eb1',
      featured: true,
    },
    {
      id: 'chrm-2025',
      title: 'CHRM - Certified Human Resource Manager',
      issuer: 'The Institute for Continuing Professional Development (ICPD)',
      year: 2025,
      category: 'Professional Certification',
      preview: '/credentials/previews/chrm-2025.webp',
      pdf: '/credentials/chrm-2025.pdf',
      featured: true,
    },
    {
      id: 'cpda-2024',
      title: 'CPDA - Certified People Development Analyst',
      issuer: 'Indonesian Human Resources Analyst Association (IHRAA)',
      year: 2024,
      category: 'People Development',
      preview: '/credentials/previews/cpda-2024.webp',
      pdf: '/credentials/cpda-2024.pdf',
      credentialId: '1220/IHRAA/CC/XII/2024',
      expiresAt: '2027-12-31',
      featured: true,
    },
    {
      id: 'empowering-leaders-2024',
      title: 'Empowering Leaders Program',
      issuer: 'KUBIK Coaching',
      year: 2024,
      category: 'Leadership Development',
      preview: '/credentials/previews/empowering-leaders-2024.webp',
      pdf: '/credentials/empowering-leaders-2024.pdf',
      featured: true,
    },
    {
      id: 'kpo-safety-2024',
      title: 'KPO Safety Refresh',
      issuer: 'PT Berau Coal - Kalimantan Timur',
      year: 2024,
      category: 'Mining & Safety',
      preview: '/credentials/previews/kpo-safety-2024.webp',
      pdf: '/credentials/kpo-safety-2024.pdf',
      credentialId: 'CPDDAS7TSZ',
      expiresAt: '2025-03-20',
    },
    {
      id: 'chrs-bnsp-2023',
      title: 'CHRS - Certified Human Resources Supervisor',
      issuer: 'BNSP - LSP Manajemen Sumber Daya Manusia Profesional',
      year: 2023,
      category: 'Professional Certification',
      preview: '/credentials/previews/chrs-bnsp-2023.webp',
      pdf: '/credentials/chrs-bnsp-2023.pdf',
      credentialId: 'M.1400.00799.2023',
      expiresAt: '2026-10-23',
      featured: true,
    },
    {
      id: 'hr-supervisor-training-2023',
      title: 'Certified HR Supervisor Training',
      issuer: 'TUK Pinasthika - Jakarta',
      year: 2023,
      category: 'HR Training',
      preview: '/credentials/previews/hr-supervisor-training-2023.webp',
      pdf: '/credentials/hr-supervisor-training-2023.pdf',
    },
    {
      id: 'qcc-facilitator-2023',
      title: 'Training QCC for Facilitator',
      issuer: 'PT Fajar Anugerah Dinamika - Jakarta',
      year: 2023,
      category: 'Operational Excellence',
      preview: '/credentials/previews/qcc-facilitator-2023.webp',
      pdf: '/credentials/qcc-facilitator-2023.pdf',
    },
    {
      id: 'pop-bnsp-2022',
      title: 'Pengawas Operasional Pertama (POP)',
      issuer: 'BNSP - LSP Pertambangan Indonesia Mandiri',
      year: 2022,
      category: 'Mining & Safety',
      preview: '/credentials/previews/pop-bnsp-2022.webp',
      pdf: '/credentials/pop-bnsp-2022.pdf',
      credentialId: 'PMB.1406.0000875.2022',
      expiresAt: '2027-06-30',
      featured: true,
    },
    {
      id: 'k3-training-2021',
      title: 'Pelatihan Keselamatan dan Kesehatan Kerja (K3)',
      issuer: 'PT Electra Global - Kalimantan Tengah',
      year: 2021,
      category: 'Mining & Safety',
      preview: '/credentials/previews/k3-training-2021.webp',
      pdf: '/credentials/k3-training-2021.pdf',
    },
    {
      id: 'public-speaking-english-2020',
      title: 'Public Speaking Training (English)',
      issuer: 'Arsikei Consulting - Jakarta',
      year: 2020,
      category: 'Communication',
      preview: '/credentials/previews/public-speaking-english-2020.webp',
      pdf: '/credentials/public-speaking-english-2020.pdf',
    },
    {
      id: 'english-job-interview-2020',
      title: 'English Job Interview',
      issuer: 'SEKOLAHMU - Jakarta',
      year: 2020,
      category: 'Communication',
      preview: '/credentials/previews/english-job-interview-2020.webp',
      pdf: '/credentials/english-job-interview-2020.pdf',
    },
    {
      id: 'diklat-teknisi-komputer-2009',
      title: 'Diklat Teknisi Komputer',
      issuer: 'Smile Group - Yogyakarta',
      year: 2009,
      category: 'Technical Training',
      preview: '/credentials/previews/diklat-teknisi-komputer-2009.webp',
      privacyProtected: true,
    },
    {
      id: 'bahasa-inggris-upper-intermediate-2008',
      title: 'Bahasa Inggris - Upper Intermediate',
      issuer: 'Practical Education Centre',
      year: 2008,
      category: 'Language Training',
      preview: '/credentials/previews/bahasa-inggris-upper-intermediate-2008.webp',
      privacyProtected: true,
    },
    {
      id: 'google-ads-video-2025',
      title: 'Google Ads Video Certification',
      issuer: 'Google',
      year: 2025,
      category: 'Digital Certification',
      preview: '/credentials/previews/google-ads-video-2025.webp',
      pdf: '/credentials/google-ads-video-2025.pdf',
      expiresAt: '2026-08-23',
    },
  ],

  education: [
    {
      degree: 'Bachelor of Law',
      institution: 'Atma Jaya University',
      period: '2005 – 2010',
      location: 'Yogyakarta - Indonesia',
    },
    {
      degree: 'Senior High School',
      institution: 'SMAN 1 Tanjung Selor',
      period: '2000 – 2002',
      location: 'Indonesia',
    },
  ],

  skills: [
    {
      category: 'Strategic HR',
      items: ['Human Capital Strategy', 'HR Strategy & Planning', 'Organizational Development', 'Industrial Relations', 'Employee Relations'],
    },
    {
      category: 'Talent Management',
      items: ['Recruitment & Talent Acquisition', 'Workforce Planning', 'Leadership Development', 'Training & Development', 'Performance Management'],
    },
    {
      category: 'HR Operations',
      items: ['HR Operations & Compliance', 'Compensation & Benefits', 'Employee Engagement', 'SOP Development', 'Budgeting & Forecasting'],
    },
    {
      category: 'Digital & Technology',
      items: ['HRIS & HR Digitalization', 'Web-Based HR Application Development', 'HR Systems', 'HR Analytics & Reporting', 'Basic Networking'],
    },
    {
      category: 'Operations',
      items: ['General Affairs Management', 'Facility Management', 'Operational Support', 'Strategic Thinking', 'Problem Solving'],
    },
  ],

  technicalSkills: [
    {
      name: 'HRIS & Web-Based HR Application Development',
      proficiency: 'Advanced',
    },
    {
      name: 'Microsoft Office & Google Workspace',
      proficiency: 'Expert',
    },
    {
      name: 'Recruitment Platforms',
      proficiency: 'Advanced',
    },
    {
      name: 'HR Reporting & Analytics',
      proficiency: 'Advanced',
    },
    {
      name: 'Performance Monitoring Systems',
      proficiency: 'Advanced',
    },
    {
      name: 'Budgeting & Forecasting',
      proficiency: 'Intermediate',
    },
    {
      name: 'Leadership Development & Training',
      proficiency: 'Expert',
    },
    {
      name: 'Basic Networking & System Support',
      proficiency: 'Intermediate',
    },
  ],

  languages: [
    {
      language: 'Bahasa Indonesia',
      proficiency: 'Native',
    },
    {
      language: 'English',
      proficiency: 'Professional Working Proficiency (C1 Advanced)',
    },
  ],

  contact: {
    email: 'yan@ym-id.com',
    phone: '+62 817393994',
    location: 'Jakarta, Indonesia',
    website: 'www.ym-id.com',
  },

  socialLinks: [
    {
      name: 'LinkedIn',
      url: 'https://linkedin.com/in/yanfirdaus',
      icon: 'linkedin',
    },
    {
      name: 'Email',
      url: 'mailto:yan@ym-id.com',
      icon: 'mail',
    },
    {
      name: 'Phone',
      url: 'tel:+62817393994',
      icon: 'phone',
    },
  ],

  gallery: [
    {
      id: 1,
      title: 'Leadership Development Training',
      caption: 'Leadership Training - Top Management',
      category: 'Leadership Development',
      image: '/gallery/la1.png',
    },
    {
      id: 2,
      title: 'Empowering Leaders Program',
      caption: 'Leadership Batch 1 - Site WBN',
      category: 'Leadership Development',
      image: '/gallery/leadership-batch2-wbn.jpg',
    },
    {
      id: 3,
      title: 'Training Activities Documentation',
      caption: 'Operator Development Program - Technical training session',
      category: 'SkillUp Dev Program',
      image: '/gallery/odp1.jpg',
    },
    {
      id: 4,
      title: 'Empowering Leaders Program',
      caption: 'Training Leadership - Level PJO',
      category: 'Leadership Development',
      image: '/gallery/leadership.png',
    },
    {
      id: 5,
      title: 'Peformance Review',
      caption: 'Meeting Peformance Review with PT Berau Coal',
      category: 'Site & Operational Activities',
      image: '/gallery/ptbc1.jpg',
    },
    {
      id: 6,
      title: 'Leadership Coaching Session',
      caption: 'Training Leadership Site HSM - Halmahera',
      category: 'Leadership Development',
      image: '/gallery/leadership-site-hsm.jpg',
    },
    {
      id: 7,
      title: 'Sosialisasi Kebijakan PT FAD Site Berau Coal',
      caption: 'PT FAD Site Berau Coal',
      category: 'Industrial Relations',
      image: '/gallery/pt-berau-coal-2.jpg',
    },
    {
      id: 8,
      title: 'Safety Awarding',
      caption: 'Best PJA - Site Berau Coal',
      category: 'Competition',
      image: '/gallery/bestpja.png',
    },
    {
      id: 9,
      title: 'Fresh Mechanic Development Program',
      caption: 'SkillUp training',
      category: 'SkillUp Dev Program',
      image: '/gallery/fmdp.png',
    },
    {
      id: 10,
      title: 'Fresh Mechanic Development Program',
      caption: 'Employee engagement and team bonding initiative',
      category: 'SkillUp Dev Program',
      image: '/gallery/fmdp2.jpg',
    },
    {
      id: 11,
      title: 'My Team',
      caption: 'HCGS PT Fajar Anugerah Dinamika Site Berau Coal',
      category: 'Site & Operational Activities',
      image: '/gallery/hcgs1.png',
    },
    {
      id: 12,
      title: 'Empowering Leaders Program',
      caption: 'Training Leadership - BSF Batch 13',
      category: 'Leadership Development',
      image: '/gallery/l13.png',
    },
    {
      id: 13,
      title: 'Empowering Leaders Program',
      caption: 'Training Leadership - Head Office',
      category: 'Leadership Development',
      image: '/gallery/lho.png',
    },
    {
      id: 14,
      title: 'Sosialiasi LSP HRS',
      caption: 'Pemaparan LSP HRS to Berau Coal',
      category: 'Site & Operational Activities',
      image: '/gallery/lsp.png',
    },
    {
      id: 15,
      title: 'HCA Annual Meeting 2024',
      caption: 'Rapat Kerja 2024',
      category: 'Corporate Events',
      image: '/gallery/raker1.png',
    },
    {
      id: 16,
      title: 'Innovaction 2024',
      caption: 'Coorporate Convention',
      category: 'Competition',
      image: '/gallery/qcc.png',
    },
    {
      id: 17,
      title: 'Empowering Leaders Program',
      caption: 'Coaching & Counceling',
      category: 'Leadership Development',
      image: '/gallery/coaching.png',
    },
    {
      id: 18,
      title: 'Best Mechanic Competition',
      category: 'Competition',
      image: '/gallery/bmc.png',
    },
    {
      id: 19,
      title: 'Empowering Leaders Program - Level PJO',
      category: 'Leadership Development',
      image: '/gallery/pjo.png',
    },
    {
      id: 20,
      title: 'Optimalisasi Program AKAD - DisnaKerTrans KalTeng',
      caption: 'PT Batara Site WAS Kalteng',
      category: 'Industrial Relations',
      image: '/gallery/disnaker.png',
    },
    {
      id: 21,
      title: 'HCGS Internal Meeting',
      category: 'Site & Operational Activities',
      image: '/gallery/hcgs.png',
    },
    {
      id: 22,
      title: 'Crusher Monitoring',
      category: 'Site & Operational Activities',
      image: '/gallery/electra.png',
    },
    {
      id: 23,
      title: 'HCGS - Raker 2024',
      caption: 'PT Fajar Anugerah Dinamika',
      category: 'Corporate Events',
      image: '/gallery/raker2024.png',
    },
    {
      id: 24,
      title: 'Certified Leadership',
      category: 'Leadership Development',
      image: '/gallery/coach.png',
    },
    {
      id: 25,
      title: 'International Judge @ China',
      caption: 'World Pump Festival',
      category: 'Corporate Events',
      image: '/gallery/judge.png',
    },
    {
      id: 26,
      title: 'Innovaction 2024 PT FAD',
      category: 'Competition',
      image: '/gallery/qcc2.png',
    },
    {
      id: 27,
      title: 'HCGS Raker 2023',
      category: 'Corporate Events',
      image: '/gallery/hcgs-raker-2023.png',
    },
    {
      id: 28,
      title: 'Office Team Site - WAS',
      category: 'Site & Operational Activities',
      image: '/gallery/hrga-site-was.png',
    },
    {
      id: 29,
      title: 'Audit DisNakerTrans KalTeng - site WAS',
      caption: 'PT Bahtera Putera Nusantara Site WAS KalTeng',
      category: 'Industrial Relations',
      image: '/gallery/ir-2.png',
    },
    {
      id: 29,
      title: 'Opening Ceremony - FMDP Batch 1',
      caption: 'Fresh Mechanic Development Program',
      category: 'SkillUp Dev Program',
      image: '/gallery/opening-fmdp.png',
    },
    {
      id: 30,
      title: 'HCGS Coordination',
      caption: 'PT FAD Site Berau Coal',
      category: 'Site & Operational Activities',
      image: '/gallery/hcgs2.png',
    },
    {
      id: 31,
      title: 'National Competition - Jakarta 2026',
      caption: 'Goes to South Asian Competition',
      category: 'Corporate Events',
      image: '/gallery/juri.png',
    },
    {
      id: 32,
      title: 'Sosialisasi Layoff',
      caption: 'PT FAD Site Berau Coal',
      category: 'Industrial Relations',
      image: '/gallery/disnaker2.png',
    },
    {
      id: 33,
      title: 'Meeting Coordination',
      caption: 'PT SSS All Site',
      category: 'Site & Operational Activities',
      image: '/gallery/sss1.png',
    },
  ],
}
